config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :splash, only: [:index]
  resources :categories do
    resources :transactions
  end
  root "splash#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Category
    can :create, Category
    can :write, Category

    can :read, Transaction
    can :create, Transaction

    return unless user.present?

    can(:destroy, Category, user:)
    can :destroy, Transaction, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  has_many :transactions, foreign_key: 'category_id', class_name: 'Transaction'

  has_one_attached :icon

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    transactions.sum(:amount)
  end
end

app/models/category_transaction.rb
class CategoryTransaction < ApplicationRecord
  belongs_to :category
  belongs_to :transaction_record, class_name: 'Transaction'
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  # associations
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :categories, dependent: :destroy

  # validations
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, class_name: 'Category', dependent: :destroy, foreign_key: 'user_id'
  has_many :transactions, class_name: 'Transaction', dependent: :destroy, foreign_key: 'user_id'

  validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_user

  def index
    @categories = current_user.categories.includes(:transactions).order(created_at: :desc)
  end

  def show
    @category = current_user.categories.find(params[:id])
    @transactions = @category.transactions.order(created_at: :desc)
    @total_amount = @transactions.sum(:amount)
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  def set_user
    @user = current_user
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_user

  def index
    @transactions = Transaction.all
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @categories = current_user.categories
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = current_user # assuming you have authentication in your app
    @category = Category.find(params[:transaction][:category_id]) # add this line
    puts @category
    if @transaction.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      @categories = current_user.categories # reassign categories to instance variable for rendering the form
      render :new
    end
  end

  def destroy
    @transaction.destroy
    redirect_to transactions_url, notice: 'Transaction was successfully destroyed.'
  end

  private

  def set_user
    @user = current_user
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id)
    # the category_ids array is used to assign categories to the transaction through the many-to-many association
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/index.html.erb
<div class="main_container">
<h1>All Categories</h1>

<% if @categories.any? %>
    <% @categories.each do |category| %>
        
      <div class="category">
        <%= image_tag category.icon,skip_pipeline: true, class:'icon'%>
        <div>
            <h3><%= link_to category.name, category_path(category) %></h3>
            <p><%= category.created_at.strftime("%d-%m-%Y") %></p>
        </div>
        <p><%= number_to_currency(category.total_amount) %></p>
       
      </div>
    <% end %> 
 <% else %>
 <p style="margin-top: 50px; text-align:center; color: orange; font-weight:bold;">
 There is no category added yet!
</p>
<% end %>

<%= link_to 'Add a new category', new_category_path, class:"button add_category" %>
<%= button_to "Log out", destroy_user_session_path,  class:"save", method: :delete %>
</div>

app/views/categories/new.html.erb
<div class="main_container">
<h1>New Category</h1>

<%= form_with model: @category, url: categories_path do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Icon %>
    <%= form.file_field :icon, class: "form-control w-50", placeholder: "Image or Icon", style: "margin-top: 26px;  margin: auto;" %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class:"save" %>
    <%= link_to 'Back', categories_path, class:"back" %>
  </div>
<% end %>
</div>

app/views/categories/show.html.erb
<div class="transaction_container">
<div class="transaction_head">
    <h3><%= @category.name %></h3>

    
    <p> <%= number_to_currency(@total_amount) %></p>

</div>

<% if @transactions.any? %>

    <% @transactions.each do |transaction| %>
      <div class="category">
        <%= image_tag @category.icon,skip_pipeline: true, class:'icon'%>
        <div>
            <p><%= transaction.name %></p>
            <p><%= number_to_currency(transaction.amount) %></p>
        </div>
        <p><%= transaction.created_at.to_date %></p>
      </div>
    <% end %>
<% else %>
    <p style="margin-top: 50px; text-align:center; color: orange; font-weight:bold;">
    There is no Transaction added for this Category yet!
   </p>
<% end %>

  <%= link_to 'Add a new transaction', new_category_transaction_path(@category), class:"button add_category" %>


<div>
  <%= link_to 'Back', categories_path, class:"back" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class="main_container">

<div class="spalsh_title">
    <p>Sign up or log in below:</p>
</div>
<div class="buttons">
  <%= link_to "LOG IN", new_user_session_path,  class: "button signin " %>
  <%= link_to "SIGN UP", new_user_registration_path, class: "button login" %>
  
</div>
</div>

app/views/transactions/new.html.erb
<div class="main_container">
<h1>New Category</h1>
<%= form_with model:@transaction, url: category_transactions_path, data: { turbo:false } do |f| %>
    <% if @transaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
        <ul>
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  
    <div class="field">
      <%= f.label :amount %>
      <%= f.number_field :amount %>
    </div>
  
    <div class="field">
      <%= f.label :category %>
      <%= f.collection_select(:category_id, Category.where(user_id: current_user.id).order(:name),:id,:name) %>
    </div>
  
    <div class="actions">
      <%= f.submit "Save" %>
      <%= link_to 'Back', categories_path, class:"back" %>
    </div>
  <% end %>
  </div>